name: Release Orchestrator Charts - Stable

on:
  workflow_dispatch:
  push:
    branches:
      - stable-1.x
    paths:
      - "charts/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add dependencies
        run: |
          helm repo add postgresql-persistent https://sclorg.github.io/helm-charts
          helm repo add backstage https://janus-idp.github.io/helm-backstage
          helm repo add workflows https://parodos.dev/serverless-workflows-config

      - name: Run chart-releaser
        uses: masayag/chart-releaser-action@main
        with:
          config: chart-releaser.yaml
          pages_index_path: docs/index.yaml
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
